# Generated by Django 4.2.1 on 2023-05-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeInformation', models.BooleanField()),
                ('name', models.CharField(max_length=10)),
                ('employeeInformationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.employeeinformation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('identificationDocument', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('mail', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=300)),
                ('identificationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.identificationtype')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.role')),
            ],
        ),
    ]
