# Generated by Django 4.2.1 on 2023-05-12 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='employeeInformationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.employeeinformation'),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.breed')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthDate', models.DateField()),
                ('color', models.CharField(max_length=20)),
                ('photo', models.CharField(max_length=300)),
                ('gender', models.CharField(max_length=10)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.species')),
            ],
        ),
    ]
